//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace prjSystem {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("rel_DS_recibo")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class rel_DS_recibo : global::System.Data.DataSet {
        
        private VWRECIBODataTable tableVWRECIBO;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public rel_DS_recibo() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected rel_DS_recibo(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["VWRECIBO"] != null)) {
                    base.Tables.Add(new VWRECIBODataTable(ds.Tables["VWRECIBO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public VWRECIBODataTable VWRECIBO {
            get {
                return this.tableVWRECIBO;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            rel_DS_recibo cln = ((rel_DS_recibo)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["VWRECIBO"] != null)) {
                    base.Tables.Add(new VWRECIBODataTable(ds.Tables["VWRECIBO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableVWRECIBO = ((VWRECIBODataTable)(base.Tables["VWRECIBO"]));
            if ((initTable == true)) {
                if ((this.tableVWRECIBO != null)) {
                    this.tableVWRECIBO.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "rel_DS_recibo";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/rel_DS_recibo.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableVWRECIBO = new VWRECIBODataTable();
            base.Tables.Add(this.tableVWRECIBO);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeVWRECIBO() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            rel_DS_recibo ds = new rel_DS_recibo();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void VWRECIBORowChangeEventHandler(object sender, VWRECIBORowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class VWRECIBODataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columncliente_id;
            
            private global::System.Data.DataColumn columnnome;
            
            private global::System.Data.DataColumn columncpf;
            
            private global::System.Data.DataColumn columnrg;
            
            private global::System.Data.DataColumn columnenderecos_id;
            
            private global::System.Data.DataColumn columnlogradouro;
            
            private global::System.Data.DataColumn columncep;
            
            private global::System.Data.DataColumn columnbairros_id;
            
            private global::System.Data.DataColumn columnbairro;
            
            private global::System.Data.DataColumn columnmunicipio_id;
            
            private global::System.Data.DataColumn columnmunicipio;
            
            private global::System.Data.DataColumn columnuf;
            
            private global::System.Data.DataColumn columnmovimentacao_id;
            
            private global::System.Data.DataColumn columnvalorpago;
            
            private global::System.Data.DataColumn columnreferencia;
            
            private global::System.Data.DataColumn columncomissaopai;
            
            private global::System.Data.DataColumn columncomissaoavo;
            
            private global::System.Data.DataColumn columnsaldo;
            
            private global::System.Data.DataColumn columnpagoa;
            
            private global::System.Data.DataColumn columnstatus;
            
            private global::System.Data.DataColumn columndatavencimento;
            
            private global::System.Data.DataColumn columndatapagamento;
            
            private global::System.Data.DataColumn columndatapagamentoavo;
            
            private global::System.Data.DataColumn columndatapagamentopai;
            
            private global::System.Data.DataColumn columnvalor;
            
            private global::System.Data.DataColumn columnnumero;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VWRECIBODataTable() {
                this.TableName = "VWRECIBO";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal VWRECIBODataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected VWRECIBODataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cliente_idColumn {
                get {
                    return this.columncliente_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn nomeColumn {
                get {
                    return this.columnnome;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cpfColumn {
                get {
                    return this.columncpf;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn rgColumn {
                get {
                    return this.columnrg;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn enderecos_idColumn {
                get {
                    return this.columnenderecos_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn logradouroColumn {
                get {
                    return this.columnlogradouro;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cepColumn {
                get {
                    return this.columncep;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn bairros_idColumn {
                get {
                    return this.columnbairros_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn bairroColumn {
                get {
                    return this.columnbairro;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn municipio_idColumn {
                get {
                    return this.columnmunicipio_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn municipioColumn {
                get {
                    return this.columnmunicipio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ufColumn {
                get {
                    return this.columnuf;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn movimentacao_idColumn {
                get {
                    return this.columnmovimentacao_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn valorpagoColumn {
                get {
                    return this.columnvalorpago;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn referenciaColumn {
                get {
                    return this.columnreferencia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn comissaopaiColumn {
                get {
                    return this.columncomissaopai;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn comissaoavoColumn {
                get {
                    return this.columncomissaoavo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn saldoColumn {
                get {
                    return this.columnsaldo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pagoaColumn {
                get {
                    return this.columnpagoa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn statusColumn {
                get {
                    return this.columnstatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn datavencimentoColumn {
                get {
                    return this.columndatavencimento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn datapagamentoColumn {
                get {
                    return this.columndatapagamento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn datapagamentoavoColumn {
                get {
                    return this.columndatapagamentoavo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn datapagamentopaiColumn {
                get {
                    return this.columndatapagamentopai;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn valorColumn {
                get {
                    return this.columnvalor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn numeroColumn {
                get {
                    return this.columnnumero;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VWRECIBORow this[int index] {
                get {
                    return ((VWRECIBORow)(this.Rows[index]));
                }
            }
            
            public event VWRECIBORowChangeEventHandler VWRECIBORowChanging;
            
            public event VWRECIBORowChangeEventHandler VWRECIBORowChanged;
            
            public event VWRECIBORowChangeEventHandler VWRECIBORowDeleting;
            
            public event VWRECIBORowChangeEventHandler VWRECIBORowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddVWRECIBORow(VWRECIBORow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VWRECIBORow AddVWRECIBORow(
                        string cliente_id, 
                        string nome, 
                        string cpf, 
                        string rg, 
                        string enderecos_id, 
                        string logradouro, 
                        string cep, 
                        string bairros_id, 
                        string bairro, 
                        string municipio_id, 
                        string municipio, 
                        string uf, 
                        string movimentacao_id, 
                        string valorpago, 
                        string referencia, 
                        string comissaopai, 
                        string comissaoavo, 
                        string saldo, 
                        string pagoa, 
                        string status, 
                        System.DateTime datavencimento, 
                        System.DateTime datapagamento, 
                        System.DateTime datapagamentoavo, 
                        System.DateTime datapagamentopai, 
                        string valor, 
                        string numero) {
                VWRECIBORow rowVWRECIBORow = ((VWRECIBORow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        cliente_id,
                        nome,
                        cpf,
                        rg,
                        enderecos_id,
                        logradouro,
                        cep,
                        bairros_id,
                        bairro,
                        municipio_id,
                        municipio,
                        uf,
                        movimentacao_id,
                        valorpago,
                        referencia,
                        comissaopai,
                        comissaoavo,
                        saldo,
                        pagoa,
                        status,
                        datavencimento,
                        datapagamento,
                        datapagamentoavo,
                        datapagamentopai,
                        valor,
                        numero};
                rowVWRECIBORow.ItemArray = columnValuesArray;
                this.Rows.Add(rowVWRECIBORow);
                return rowVWRECIBORow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                VWRECIBODataTable cln = ((VWRECIBODataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new VWRECIBODataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columncliente_id = base.Columns["cliente_id"];
                this.columnnome = base.Columns["nome"];
                this.columncpf = base.Columns["cpf"];
                this.columnrg = base.Columns["rg"];
                this.columnenderecos_id = base.Columns["enderecos_id"];
                this.columnlogradouro = base.Columns["logradouro"];
                this.columncep = base.Columns["cep"];
                this.columnbairros_id = base.Columns["bairros_id"];
                this.columnbairro = base.Columns["bairro"];
                this.columnmunicipio_id = base.Columns["municipio_id"];
                this.columnmunicipio = base.Columns["municipio"];
                this.columnuf = base.Columns["uf"];
                this.columnmovimentacao_id = base.Columns["movimentacao_id"];
                this.columnvalorpago = base.Columns["valorpago"];
                this.columnreferencia = base.Columns["referencia"];
                this.columncomissaopai = base.Columns["comissaopai"];
                this.columncomissaoavo = base.Columns["comissaoavo"];
                this.columnsaldo = base.Columns["saldo"];
                this.columnpagoa = base.Columns["pagoa"];
                this.columnstatus = base.Columns["status"];
                this.columndatavencimento = base.Columns["datavencimento"];
                this.columndatapagamento = base.Columns["datapagamento"];
                this.columndatapagamentoavo = base.Columns["datapagamentoavo"];
                this.columndatapagamentopai = base.Columns["datapagamentopai"];
                this.columnvalor = base.Columns["valor"];
                this.columnnumero = base.Columns["numero"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columncliente_id = new global::System.Data.DataColumn("cliente_id", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncliente_id);
                this.columnnome = new global::System.Data.DataColumn("nome", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnome);
                this.columncpf = new global::System.Data.DataColumn("cpf", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncpf);
                this.columnrg = new global::System.Data.DataColumn("rg", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrg);
                this.columnenderecos_id = new global::System.Data.DataColumn("enderecos_id", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnenderecos_id);
                this.columnlogradouro = new global::System.Data.DataColumn("logradouro", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlogradouro);
                this.columncep = new global::System.Data.DataColumn("cep", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncep);
                this.columnbairros_id = new global::System.Data.DataColumn("bairros_id", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbairros_id);
                this.columnbairro = new global::System.Data.DataColumn("bairro", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbairro);
                this.columnmunicipio_id = new global::System.Data.DataColumn("municipio_id", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmunicipio_id);
                this.columnmunicipio = new global::System.Data.DataColumn("municipio", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmunicipio);
                this.columnuf = new global::System.Data.DataColumn("uf", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnuf);
                this.columnmovimentacao_id = new global::System.Data.DataColumn("movimentacao_id", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmovimentacao_id);
                this.columnvalorpago = new global::System.Data.DataColumn("valorpago", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnvalorpago);
                this.columnreferencia = new global::System.Data.DataColumn("referencia", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnreferencia);
                this.columncomissaopai = new global::System.Data.DataColumn("comissaopai", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncomissaopai);
                this.columncomissaoavo = new global::System.Data.DataColumn("comissaoavo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncomissaoavo);
                this.columnsaldo = new global::System.Data.DataColumn("saldo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsaldo);
                this.columnpagoa = new global::System.Data.DataColumn("pagoa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpagoa);
                this.columnstatus = new global::System.Data.DataColumn("status", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstatus);
                this.columndatavencimento = new global::System.Data.DataColumn("datavencimento", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndatavencimento);
                this.columndatapagamento = new global::System.Data.DataColumn("datapagamento", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndatapagamento);
                this.columndatapagamentoavo = new global::System.Data.DataColumn("datapagamentoavo", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndatapagamentoavo);
                this.columndatapagamentopai = new global::System.Data.DataColumn("datapagamentopai", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndatapagamentopai);
                this.columnvalor = new global::System.Data.DataColumn("valor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnvalor);
                this.columnnumero = new global::System.Data.DataColumn("numero", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnumero);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VWRECIBORow NewVWRECIBORow() {
                return ((VWRECIBORow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new VWRECIBORow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(VWRECIBORow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.VWRECIBORowChanged != null)) {
                    this.VWRECIBORowChanged(this, new VWRECIBORowChangeEvent(((VWRECIBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.VWRECIBORowChanging != null)) {
                    this.VWRECIBORowChanging(this, new VWRECIBORowChangeEvent(((VWRECIBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.VWRECIBORowDeleted != null)) {
                    this.VWRECIBORowDeleted(this, new VWRECIBORowChangeEvent(((VWRECIBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.VWRECIBORowDeleting != null)) {
                    this.VWRECIBORowDeleting(this, new VWRECIBORowChangeEvent(((VWRECIBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveVWRECIBORow(VWRECIBORow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                rel_DS_recibo ds = new rel_DS_recibo();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "VWRECIBODataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class VWRECIBORow : global::System.Data.DataRow {
            
            private VWRECIBODataTable tableVWRECIBO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal VWRECIBORow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableVWRECIBO = ((VWRECIBODataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cliente_id {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.cliente_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cliente_id\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.cliente_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string nome {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.nomeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nome\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.nomeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cpf {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.cpfColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cpf\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.cpfColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string rg {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.rgColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'rg\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.rgColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string enderecos_id {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.enderecos_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'enderecos_id\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.enderecos_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string logradouro {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.logradouroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'logradouro\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.logradouroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cep {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.cepColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cep\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.cepColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string bairros_id {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.bairros_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bairros_id\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.bairros_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string bairro {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.bairroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bairro\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.bairroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string municipio_id {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.municipio_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'municipio_id\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.municipio_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string municipio {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.municipioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'municipio\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.municipioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string uf {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.ufColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'uf\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.ufColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string movimentacao_id {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.movimentacao_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'movimentacao_id\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.movimentacao_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string valorpago {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.valorpagoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'valorpago\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.valorpagoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string referencia {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.referenciaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'referencia\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.referenciaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string comissaopai {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.comissaopaiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'comissaopai\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.comissaopaiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string comissaoavo {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.comissaoavoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'comissaoavo\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.comissaoavoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string saldo {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.saldoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'saldo\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.saldoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pagoa {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.pagoaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pagoa\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.pagoaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string status {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.statusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'status\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime datavencimento {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableVWRECIBO.datavencimentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'datavencimento\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.datavencimentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime datapagamento {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableVWRECIBO.datapagamentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'datapagamento\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.datapagamentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime datapagamentoavo {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableVWRECIBO.datapagamentoavoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'datapagamentoavo\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.datapagamentoavoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime datapagamentopai {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableVWRECIBO.datapagamentopaiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'datapagamentopai\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.datapagamentopaiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string valor {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.valorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'valor\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.valorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string numero {
                get {
                    try {
                        return ((string)(this[this.tableVWRECIBO.numeroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'numero\' in table \'VWRECIBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableVWRECIBO.numeroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscliente_idNull() {
                return this.IsNull(this.tableVWRECIBO.cliente_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcliente_idNull() {
                this[this.tableVWRECIBO.cliente_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnomeNull() {
                return this.IsNull(this.tableVWRECIBO.nomeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnomeNull() {
                this[this.tableVWRECIBO.nomeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscpfNull() {
                return this.IsNull(this.tableVWRECIBO.cpfColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcpfNull() {
                this[this.tableVWRECIBO.cpfColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsrgNull() {
                return this.IsNull(this.tableVWRECIBO.rgColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetrgNull() {
                this[this.tableVWRECIBO.rgColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isenderecos_idNull() {
                return this.IsNull(this.tableVWRECIBO.enderecos_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setenderecos_idNull() {
                this[this.tableVWRECIBO.enderecos_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IslogradouroNull() {
                return this.IsNull(this.tableVWRECIBO.logradouroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetlogradouroNull() {
                this[this.tableVWRECIBO.logradouroColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscepNull() {
                return this.IsNull(this.tableVWRECIBO.cepColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcepNull() {
                this[this.tableVWRECIBO.cepColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isbairros_idNull() {
                return this.IsNull(this.tableVWRECIBO.bairros_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setbairros_idNull() {
                this[this.tableVWRECIBO.bairros_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbairroNull() {
                return this.IsNull(this.tableVWRECIBO.bairroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbairroNull() {
                this[this.tableVWRECIBO.bairroColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ismunicipio_idNull() {
                return this.IsNull(this.tableVWRECIBO.municipio_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setmunicipio_idNull() {
                this[this.tableVWRECIBO.municipio_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsmunicipioNull() {
                return this.IsNull(this.tableVWRECIBO.municipioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetmunicipioNull() {
                this[this.tableVWRECIBO.municipioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsufNull() {
                return this.IsNull(this.tableVWRECIBO.ufColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetufNull() {
                this[this.tableVWRECIBO.ufColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ismovimentacao_idNull() {
                return this.IsNull(this.tableVWRECIBO.movimentacao_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setmovimentacao_idNull() {
                this[this.tableVWRECIBO.movimentacao_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsvalorpagoNull() {
                return this.IsNull(this.tableVWRECIBO.valorpagoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetvalorpagoNull() {
                this[this.tableVWRECIBO.valorpagoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsreferenciaNull() {
                return this.IsNull(this.tableVWRECIBO.referenciaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetreferenciaNull() {
                this[this.tableVWRECIBO.referenciaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscomissaopaiNull() {
                return this.IsNull(this.tableVWRECIBO.comissaopaiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcomissaopaiNull() {
                this[this.tableVWRECIBO.comissaopaiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscomissaoavoNull() {
                return this.IsNull(this.tableVWRECIBO.comissaoavoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcomissaoavoNull() {
                this[this.tableVWRECIBO.comissaoavoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssaldoNull() {
                return this.IsNull(this.tableVWRECIBO.saldoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsaldoNull() {
                this[this.tableVWRECIBO.saldoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IspagoaNull() {
                return this.IsNull(this.tableVWRECIBO.pagoaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetpagoaNull() {
                this[this.tableVWRECIBO.pagoaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsstatusNull() {
                return this.IsNull(this.tableVWRECIBO.statusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetstatusNull() {
                this[this.tableVWRECIBO.statusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsdatavencimentoNull() {
                return this.IsNull(this.tableVWRECIBO.datavencimentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetdatavencimentoNull() {
                this[this.tableVWRECIBO.datavencimentoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsdatapagamentoNull() {
                return this.IsNull(this.tableVWRECIBO.datapagamentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetdatapagamentoNull() {
                this[this.tableVWRECIBO.datapagamentoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsdatapagamentoavoNull() {
                return this.IsNull(this.tableVWRECIBO.datapagamentoavoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetdatapagamentoavoNull() {
                this[this.tableVWRECIBO.datapagamentoavoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsdatapagamentopaiNull() {
                return this.IsNull(this.tableVWRECIBO.datapagamentopaiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetdatapagamentopaiNull() {
                this[this.tableVWRECIBO.datapagamentopaiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsvalorNull() {
                return this.IsNull(this.tableVWRECIBO.valorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetvalorNull() {
                this[this.tableVWRECIBO.valorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnumeroNull() {
                return this.IsNull(this.tableVWRECIBO.numeroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnumeroNull() {
                this[this.tableVWRECIBO.numeroColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class VWRECIBORowChangeEvent : global::System.EventArgs {
            
            private VWRECIBORow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VWRECIBORowChangeEvent(VWRECIBORow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VWRECIBORow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591